### ISSUE TITLE
Could we have a new release please?

### ISSUE THREAD

**Issue by JerrySheaB4** [aeischeid/grails-pdfplugin#2]
It's just that the latest one you can download using install-plugin (0.4) has a problem when you install it with copying demo.gsp (see http://n4.nabble.com/What-happened-to-the-pdf-plugin-td1333290.html#a1333290).
I see that the _Install.groovy script has been fixed in git already so all that needs doing is a new release :)
Thanks

**Comment by aeischeid** [comment]
you're welcome ;)
