### ISSUE TITLE
images in https context

### ISSUE THREAD

**Issue by hitty5** [aeischeid/grails-pdfplugin#3]
i'm using plugin version 4.5 and  grails 1.1.1. I'm creating pdf file with pdfForm tag and a controller action. Within the gsp which is rendered as PDF some images are referneced with normal <img> tags. In normal http context all images are displayed. in a secured web app (https) those images will not be displayed. i also tried diffrend methods (pdfLink, ..), but no success.

Please can you tell me, whether there a known prolbems with https or no. thanks you very much!

**Comment by aeischeid** [comment]
i haven't tested with https at all. I will give it a try.
