### ISSUE TITLE
Error using &nbsp; &aacute;

### ISSUE THREAD

**Issue by henrystivens** [aeischeid/grails-pdfplugin#4]
Error using &nbsp; &aacutte;

ERROR:  'The entity "aacute" was referenced, but not declared.'
ERROR:  'The entity "nbsp" was referenced, but not declared.'

problem with ampersand?

**Comment by aeischeid** [comment]
need to look into this one. did you try escaping the & ?

**Comment by henrystivens** [comment]
how to escaping the &?

**Comment by aeischeid** [comment]
\

**Comment by henrystivens** [comment]
thanks.
