### ISSUE TITLE
iText conflict

### ISSUE THREAD

**Issue by ecodan** [aeischeid/grails-pdfplugin#5]
Aaron- 

I've been trying to get PDF plugin to work alongside Jasper.  There appears to be a conflict with the iText lib... at around 2.1.2, there was an API change that seems to be causing lots of fits.  Jasper is uing 2.1.7-ish, and I noticed that PDF is using 2.0.x.  Here's the error that shows up in the logs:

there was a problem with PDF generation java.lang.NoSuchMethodError: com.lowagie.text.pdf.BaseFont.getCharBBox(C)[I

From what I can see on the boards, resolving this simply requires a recompile (and possibly a cast) using a post 2.1.2 version of iText.  Could we get a build that has the latest iText to see if it clears up the issue? 

Thanks for contributing this plugin to the grails community!

**Comment by aeischeid** [comment]
I will test it out with updated iText and see what happens. There must be some way for plugins to not include duplicates of dependencies. gotta look into that too.

**Comment by aeischeid** [comment]
iText changed

from:
    public int[] getCharBBox(char c) {
        byte b[] = convertToBytes(c);
        if (b.length == 0)
            return null;
        else
            return charBBoxes[b[0] & 0xff];
    }

to:
    public int[] getCharBBox(int c) {
        byte b[] = convertToBytes(c);
        if (b.length == 0)
            return null;
        else
            return charBBoxes[b[0] & 0xff];
    }

that seems to be what would cause the issue. Should I get in and change the xhtmlRenderer and recompile that or change iText?

**Comment by aeischeid** [comment]
I think we will just have to wait for the flying saucer project to put out a new release. in the mean time the FS mailing list had this suugestion

Perhaps jarjar (http://code.google.com/p/*jarjar*/) can help you.

**Comment by ecodan** [comment]
Hmmm... interesting.  You're probably right.  I think what we'll have to do is just natively use the iText JAR (without the help of your plugin) and futz with it until we get the version mismatches worked out.  Thanks for looking into this!
